name: Update NSE Stocks to Google Sheet

permissions:
  contents: write
  id-token: write
on:
  schedule:
    # Run at 16:00 (UTC) every day from Monday to Saturday
    - cron: '0 16 * * 1-6'
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Libraries
        run: pip install gspread oauth2client pandas requests

      - name: Run Python Script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python src/data_acquisition/update_sheet.py

      - name: Commit Historical Data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add data/historical/*.csv

          git diff --staged --quiet || git commit -m "Add NSE historical data"

          git push